version: '3'
services:
  mysql:
    image: mysql:8
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_TABLE_NAME}
    volumes:
      - ./vanneurs-db:/var/lib/mysql
    ports:
      - "${MYSQL_EXTERNAL_PORT}:${MYSQL_PORT}"
  api:
    build: ./vanneurs-api
    ports:
      - "${API_EXTERNAL_PORT}:${API_PORT}"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:${MYSQL_PORT}/${MYSQL_TABLE_NAME}?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${MYSQL_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
  react:
    build: ./vanneurs-front
    ports:
      - "${REACT_EXTERNAL_PORT}:${REACT_PORT}"
